name: Automate BSN

on:
  push:
    branches:
      - main
  workflow_dispatch:
#  schedule:
#    - cron: "0 10 * * 1,2,3,4,5"
    # Asia/Kuala_Lumpur around 6pm, weekdays only

jobs:
  automation:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.12.0'

      - name: Install packages
        run: yarn install

      - name: Install playwright's chrome
        run: npx playwright install-deps chromium

      - uses: c-hive/gha-yarn-cache@v2

      - name: Run BSN
        run: yarn bsn
        env:
          ICS: ${{ secrets.ICS }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
