name: Automate BSN

on:
  push:
    branches:
      - tests
  workflow_dispatch:
#  schedule:
#    - cron: "0 10 * * 1,2,3,4,5"
    # Asia/Kuala_Lumpur around 6pm, weekdays only

jobs:
  automation:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.12.0'
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install packages
        run: yarn install

      - name: Install playwright's chrome
        run: npx playwright install-deps chromium

      - uses: nick-invision/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 3
          command: yarn bsn
        env:
          ICS: ${{ secrets.ICS }}
          NODE_ENV: ${{ secrets.NODE_ENV }}

      - name: Run BSN
        run: yarn bsn
        env:
          ICS: ${{ secrets.ICS }}
          NODE_ENV: ${{ secrets.NODE_ENV }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add test
