name: Automate BSN

on:
  push:
    branches:
      - main
  workflow_dispatch:
#  schedule:
#    - cron: "0 10 * * 1,2,3,4,5"
    # Asia/Kuala_Lumpur around 6pm, weekdays only

jobs:
  automation:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.12.0'
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install packages
        run: yarn install

      - name: Install playwright's chrome
        run: npx playwright install-deps chromium

      - name: Run BSN
        run: yarn bsn
        env:
          ICS: ${{ secrets.ICS }}
          NODE_ENV: ${{ secrets.NODE_ENV }}

#      - name: Commit changes
#        uses: EndBug/add-and-commit@v7.2.1
#        with:
#          author_name: azrizhaziq
#          author_email: azrizhaziq@gmail.com
#          message: "Add screenshot and video"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
