name: Automate

on:
  push:
    branches:
      - test
  workflow_dispatch:
#  schedule:
#    - cron: "0 10 * * 1,2,3,4,5"
    # Asia/Kuala_Lumpur around 6pm, weekdays only

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.12.0'
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install packages
        run: yarn install

      - name: Run automation test
        id: automation_test
        run: yarn test
        env:
          ICS: ${{ secrets.ICS }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          MITI_PASS: ${{ secrets.MITI_PASS }}

      - name: Run update snapshot
        if: ${{ failure() }}
        run: yarn test:update
        env:
          ICS: ${{ secrets.ICS }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          MITI_PASS: ${{ secrets.MITI_PASS }}

      - name: Send to telegram
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: The ${{ github.event_name }} event triggered first step.
          debug: true

      - name: Commit new changes
        if: ${{ failure() }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add test
