name: Run test

on:
   push:
     branches:
       - test

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.12.0'

      - name: Run this on CI
        run: npm run dummy
