name: Update Snapshot

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Automate"]
    types:
      - completed

jobs:
  automation:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.12.0'
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install packages
        run: yarn install

      - name: Updating snapshot
        run: yarn test:update
        env:
          ICS: ${{ secrets.ICS }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          MITI_PASS: ${{ secrets.MITI_PASS }}

#      - uses: stefanzweifel/git-auto-commit-action@v4
#        if: ${{ success() && steps.automation_test.outputs.result == 'failure' }}
#        with:
#          commit_message: Add test
